---
output:html_document
---

```{r}
library(tidyverse)
library(untidydata)

# these two lines are the same; you can use either or
mtcars %>% select()

select(mtcars, mpg, hp, disp)

select(mtcars, am, gear, carb)

# rename a variable, like in this case, I renamed mpg to hello_world
select(mtcars, hello_world = mpg)

# this part selects data for variables that start with a certain letter
select(mtcars, starts_with("d"))

# use to filter rows

# filter when mpy is less than 20 and greater than 14
filter(mtcars, mpg < 20 & mpg > 14)

# filter to when cyl is equal to 6
filter(mtcars, cyl == 6)

# filter when mpg is greater than 20 or disp is less than 200
filter(mtcars, mpg > 20 | disp < 200)

# use mutate when you want to add a new column

mtcars %>%
  select(mpg) %>%
  mutate(., mpg_x2 = mpg * 2)


mtcars %>%
  select(mpg) %>%
  mutate(., mpg_c = mpg - mean(mpg))

# if else condition if mpg is greater than 18 it is good, else
# it is labeled bad 

mtcars %>%
  select(mpg) %>%
  mutate(., value = if_else(mpg > 18, "good", "bad"))
  
# summarize 

mtcars %>%
summarize(., mean_mpg = mean(mpg))

mtcars %>%
  group_by(., cyl) %>%
  summarize(., mean_mpg = mean(mpg))

mtcars %>%
  group_by(., cyl) %>%
  summarize(., mean_mpg = mean(mpg) , 
            sd_mpg = sd(mpg),
            min_mpg = min(mpg),
            max_mpg = max(mpg))
```

``` {r}
# data from untidydata set
library(untidydata)
# separate into different columns 

pre_post %>%
  separate(., col = spec,
           into = c( "group", "cond"), 
           sep = "_")
            
#unite into one column 

pre_post %>% 
unite(., col = "silly", 
c("id", "spec"),
sep = "_")
            
#pivot_longer

pre_post %>%
  pivot_longer(., 
               cols = "test1", "test2",
               names_to = "test",
               values_to = "score") %>%
  ggplot(., aes(x = test, y = score)) +
              geom_boxplot()
            
#pivot_wider 

language_diversity %>% glimpse
            
language_diversity %>%
              pivot_wider(
                id_cols = ,
                names_from = ,
                values_from = 
                  )
```              

